### ISSUE TITLE
大佬您好，我可以请教您一个问题吗？

### ISSUE THREAD

**Issue by 1BenBenHui** [ZhenbangDu/Seizure_MoE#1]
关于model模型的输入x应该是什么维度呢？我输入的是四维度：[batch_size, 20, 1, 512]，它对EEGNet是可行的，但是对model并不可行，所以请问具体的x的输入应该是什么样的，以及输入时如何将原始的eeg和Manual Features（是[20, 2]维度吗？）进行拼凑呢？如果您能回答，非常感激！

**Comment by 1BenBenHui** [comment]
这是我的email：HellebautEsco967@gmail.com,非常感谢！

**Comment by 1BenBenHui** [comment]
或者这是我的QQ：2194746186，谢谢！

**Comment by ZhenbangDu** [comment]
hello，我添加你qq了

> 或者这是我的QQ：2194746186，谢谢！
